version: '3'

services:
  frontend:
    container_name: frontend
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
