version: '3'

services:
  frontend:
    image: nikola/frontend
    container_name: frontend
    env_file:
      - ../.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_INTERNAL_BACKEND_URL: ${NEXT_PUBLIC_INTERNAL_BACKEND_URL}
        NEXT_PUBLIC_BACKEND_DOMAIN: ${NEXT_PUBLIC_BACKEND_DOMAIN}
    ports:
      - "3000:3000"
    networks:
      - nikola-docker-network

volumes:
  app_node_modules:
  app_next:

networks:
  nikola-docker-network:
    external: true
