import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import Head from "next/head";

const montserrat = Montserrat({ 
  weight: ["100", "200", "300", "400", "600", "700"], 
  variable: "--montserrat-font",
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;



}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="/favicon.ico"/>
      </Head>
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
